namespace ASP_.NET_InvoiceManagementAuth.Models;

/// <summary>
/// Represents a file attachment associated with a specific invoice.
/// Stores metadata required to locate the file in physical storage and track its origin.
/// </summary>
public class InvoiceAttachment
{
    /// <summary>
    /// Unique identifier for the attachment record.
    /// </summary>
    public int Id { get; set; }

    /// <summary>
    /// Foreign key referencing the associated <see cref="Invoice"/>.
    /// </summary>
    public Guid InvoiceId { get; set; }

    /// <summary>
    /// Navigation property for the parent invoice.
    /// </summary>
    public virtual Invoice Invoice { get; set; } = null!;

    /// <summary>
    /// The original name of the file as uploaded by the user.
    /// Used for display purposes when downloading.
    /// </summary>
    /// <example>receipt_january_2024.pdf</example>
    public string OriginalFileName { get; set; } = string.Empty;

    /// <summary>
    /// The unique filename generated by the system (usually a GUID) used for physical storage.
    /// This prevents filename collisions on the disk.
    /// </summary>
    public string StoredFileName { get; set; } = string.Empty;

    /// <summary>
    /// The MIME type of the file (e.g., application/pdf, image/png).
    /// </summary>
    public string ContentType { get; set; } = string.Empty;

    /// <summary>
    /// The size of the file in bytes.
    /// </summary>
    public long Size { get; set; }

    /// <summary>
    /// The ID of the <see cref="AppUser"/> who performed the upload.
    /// </summary>
    public string UploadedUserId { get; set; } = string.Empty;

    /// <summary>
    /// Navigation property for the user who uploaded the file.
    /// </summary>
    public virtual AppUser UploadedUser { get; set; } = null!;

    /// <summary>
    /// The timestamp (UTC) when the file was successfully stored and registered.
    /// </summary>
    public DateTimeOffset UploadedAt { get; set; }
}